version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      # This maps the local nginx.conf file to the container's configuration.
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend/rag-admin-frontend
      dockerfile: Dockerfile
    container_name: rag-admin-frontend
    environment:
      # The API URL uses the Docker service name 'backend' and its internal port.
      - NEXT_PUBLIC_API_URL=http://backend:8000
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    environment:
      - DATABASE_URI=postgresql://postgres:123@postgres_db:5432/multi_tenant_admin
    depends_on:
      - postgres_db
      - chroma_db

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=multi_tenant_admin
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
  chroma_db:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma_db
    volumes:
      - chroma_data:/chroma
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      # These are the login credentials for the pgAdmin web UI.
      - PGADMIN_DEFAULT_EMAIL=nitesh@dotstark.com
      - PGADMIN_DEFAULT_PASSWORD=sa123
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

volumes:
  postgres_data:
  chroma_data: